#apiVersion: v1
#kind: Pod
#metadata:
#  name: nodejs-app
#  namespace: default
#spec:
#  containers:
#  - name: nodejs-app
#    image: helloapp:v1
#    resources:
#      limits:
#        memory: "200Mi"
#      requests:
#        memory: "100Mi"
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  ports:
  - port: 80
  selector:
    app: nodejs-app
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - image: nodejs-app
        name: nodejs-app
        env:
        ports:
        - containerPort: 80
          name: nodejs-app
